services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filmflix-back
    ports:
      - "8080:8080"
    depends_on:
      - filmflix_db
    environment:
      - DB_HOST=filmflix_db
      - DB_PORT=5432
      - DB_NAME=filmflix_db
      - DB_USER=postgres
      - DB_PASSWORD=dbpassword1234
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH:-./firebasekeys.json}
      - FIREBASE_BUCKET_NAME=${FIREBASE_BUCKET_NAME}
    networks:
      - filmflix-network
    restart: unless-stopped

  filmflix_db:
    image: postgres:15-alpine
    container_name: filmflix_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=filmflix_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpassword1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - filmflix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  filmflix-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local